composite_leave_types 		= LeaveType.where(:company_id => @leave_type.company_id, :is_composite => false, :special_leave => false, :is_active => true)
composite_leave_type_ids 	= @leave_type.composite_leave_types.collect(&:merge_leave_type_id)
json.leave_type do
  json.id           													@leave_type.try(:id)
  json.company_id 														@leave_type.try(:company_id)
  json.location_id 														@leave_type.try(:location_id)
	json.name 																	@leave_type.try(:name)
	json.short_name 														@leave_type.try(:short_name)
	json.sort_order 														@leave_type.try(:sort_order)
	json.gender 																@leave_type.try(:gender)
	json.tenure 																@leave_type.try(:tenure)
	json.eligible 															@leave_type.try(:eligible)
	json.encashment_applicable 									@leave_type.try(:encashment_applicable)
	json.limit_request_tenure 									@leave_type.try(:limit_request_tenure)
	json.is_active 															@leave_type.try(:is_active)
	json.is_deductible 													@leave_type.try(:is_deductible)
	json.sandwich 															@leave_type.try(:sandwich)
	json.splitable 															@leave_type.try(:splitable)
	json.can_apply_in_probation 								@leave_type.try(:can_apply_in_probation)
	json.pro_rated 															@leave_type.try(:pro_rated)
	json.can_apply_for_remaining_leave 					@leave_type.try(:can_apply_for_remaining_leave)
	json.back_date_apply 												@leave_type.try(:back_date_apply)
	json.encashment 														@leave_type.try(:encashment)
	json.carry_forward 													@leave_type.try(:carry_forward)
	json.limit_request_in_tenure 								@leave_type.try(:limit_request_in_tenure)
	json.accumulative_count 										@leave_type.try(:accumulative_count)
	json.min_day_for_apply_leave 								@leave_type.try(:min_day_for_apply_leave)
	json.min_experience_to_availed_leave 				@leave_type.try(:min_experience_to_availed_leave)
	json.limit_request_count 										@leave_type.try(:limit_request_count)
	json.back_date_limit 												@leave_type.try(:back_date_limit)
	json.encashment_min_limit 									@leave_type.try(:encashment_min_limit)
	json.encashment_max_limit 									@leave_type.try(:encashment_max_limit)
	json.carry_forward_min_limit 								@leave_type.try(:carry_forward_min_limit)
	json.carry_forward_max_limit 								@leave_type.try(:carry_forward_max_limit)
	json.description 														@leave_type.try(:description)
	json.quota_allocation												@leave_type.try(:quota_allocation)
	json.earned_quota														@leave_type.try(:earned_quota)
	json.earned_quota_max_limit									@leave_type.try(:earned_quota_max_limit)
	json.auto_allocation												@leave_type.try(:auto_allocation)
	json.special_leave													@leave_type.try(:special_leave)
	json.no_of_years														@leave_type.try(:no_of_years)
	json.backdate_quota													@leave_type.try(:backdate_quota)
	json.skipped_joining_month									@leave_type.try(:skipped_joining_month)
	json.is_composite														@leave_type.try(:is_composite)
	json.attendance_restricted 									@leave_type.try(:attendance_restricted)
	json.attendance_restricted_applicable 			@leave_type.try(:attendance_restricted_applicable)
	json.transfer_probation_balance 						@leave_type.try(:transfer_probation_balance)
	json.no_of_absent 													@leave_type.try(:no_of_absent)
	json.is_leave_without_pay 									@leave_type.try(:is_leave_without_pay)
	json.experience_type 												@leave_type.try(:experience_type)
	json.probation_limit_request_in_tenure			@leave_type.try(:probation_limit_request_in_tenure)
	json.probation_limit_request_tenure 				@leave_type.try(:probation_limit_request_tenure)
	json.probation_limit_request_count 					@leave_type.try(:probation_limit_request_count)
	json.composite_leave_types composite_leave_types.order('id ASC') do |composite_leave_type|
	  if composite_leave_type_ids.include?(composite_leave_type.id)
			alloocated_leave_type = CompositeLeaveType.find_by(:leave_type_id => @leave_type.id, :merge_leave_type_id => composite_leave_type.id)
	  	json.composite_leave_type_id   						alloocated_leave_type.try(:id)
		  json.id   																alloocated_leave_type.combine_leave_type.try(:id)
		  json.name 																alloocated_leave_type.combine_leave_type.try(:name)
			json.status 															alloocated_leave_type.try(:status)
		else
			json.id   																composite_leave_type.try(:id)
		  json.name 																composite_leave_type.try(:name)
			json.status 															"Not Allowed"
	  end
  end
    json.grade_ids @leave_type.grade_ids.nil? ? [] : @leave_type.try(:grade_ids).split(',').map(&:to_i)
end