json.employees @employees.each do |employee|
	json.employee_code 					employee.employee_code
	json.full_name 							employee.full_name
	json.grade_name 						employee.grade_name
	json.designation_name 			employee.designation_name
	json.location_name 					employee.location_name
	json.branch_name 						employee.branch_name
	json.department_name 				employee.department_name
	json.job_title_name 				employee.job_title_name
	json.health_insurance				ReportFormat.boolean_in_text_as_allowed(employee.health_insurance_allowed)
	json.group_life_insurance		ReportFormat.boolean_in_text_as_allowed(employee.life_insurance_allowed)
	json.social_security				ReportFormat.boolean_in_text_as_allowed(employee.social_security_allowed)
	json.cell_phone_bill				ReportFormat.boolean_in_text_as_allowed(employee.cell_phone_bill_allowed)
	json.fuel										ReportFormat.boolean_in_text_as_allowed(employee.fuel_allowed)
	json.cell_phone							ReportFormat.boolean_in_text_as_allowed(employee.cell_phone_allowed)
	json.laptop									ReportFormat.boolean_in_text_as_allowed(employee.laptop_allowed)
	json.vehicle								ReportFormat.boolean_in_text_as_allowed(employee.velicle_allowed)
	json.provident_fund					ReportFormat.boolean_in_text_as_allowed(employee.provident_fund_allowed)
	json.eobi										ReportFormat.boolean_in_text_as_allowed(employee.eobi_allowed)
	json.incentive							ReportFormat.boolean_in_text_as_allowed(employee.incentive_allowed)
	json.vehicle_allowance			ReportFormat.boolean_in_text_as_allowed(employee.vehicle_allowance_allowed)
	json.maintenance_allowance	ReportFormat.boolean_in_text_as_allowed(employee.maintenance_allowed)
	json.travel_allowance				ReportFormat.boolean_in_text_as_allowed(employee.travel_allowance_allowed)
	json.first_eid							ReportFormat.boolean_in_text_as_allowed(employee.bonus1_allowed)
	json.second_eid							ReportFormat.boolean_in_text_as_allowed(employee.bonus2_allowed)
	json.annual_bonus						ReportFormat.boolean_in_text_as_allowed(employee.bonus3_allowed)
	json.overtime								ReportFormat.boolean_in_text_as_allowed(employee.is_overtime)
	json.is_holiday_overtime		ReportFormat.boolean_in_text_as_allowed(employee.is_holiday_overtime)
	json.off_day								ReportFormat.boolean_in_text_as_allowed(employee.is_off_day_working)
	json.cpl										ReportFormat.boolean_in_text_as_allowed(employee.is_cpl)
	json.is_regular_cpl					ReportFormat.boolean_in_text_as_allowed(employee.is_regular_cpl)
	json.attendance_exempted		ReportFormat.boolean_in_text_as_allowed(employee.attendance_exempted)
	json.tax_exempted						ReportFormat.boolean_in_text_as_allowed(employee.tax_exempted)
	json.salary_exempted				ReportFormat.boolean_in_text_as_allowed(employee.salary_exempted)
	json.back_date_allowance		ReportFormat.boolean_in_text_as_allowed(employee.back_date_allowance_impact)
	json.back_date_pf						ReportFormat.boolean_in_text_as_allowed(employee.back_date_pf_impact)
	json.back_date_eobi 				ReportFormat.boolean_in_text_as_allowed(employee.back_date_eobi_impact)
end