development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  base_url: <%= ENV["BASE_URL"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  base_url: <%= ENV["BASE_URL"] %>
